image upload
MathiasHobler/capstone-project pull request #42
Opened 2022-07-11 07:06 UTC by MathiasHobler

2022-07-11 10:16 UTC, macfrei reviewed
Just one minor comment :)

2022-07-11 10:16 UTC, macfrei commented on src/components/Inputfield/ImageInput.jsx
> +				Authorization: `Client-ID fc88c8f5835b3ec`,
Is this not supposed to be a secret? 🤔

2022-07-13 13:58 UTC, stefankorder requested changes
Good work! There are just two unneeded console logs in your code.

2022-07-13 13:58 UTC, stefankorder commented on api/imgur/upload.js
> +			console.log(request.body);
Please delete this console log.

2022-07-13 13:58 UTC, stefankorder commented on src/components/Inputfield/ImageInput.jsx
> +			console.log(data.url);
Please delete this console los.

2022-07-13 14:07 UTC, MathiasHobler commented on api/imgur/upload.js
> +			console.log(request.body);
Done

2022-07-13 14:55 UTC, stefankorder approved these changes
Good work!

2022-07-14 09:12 UTC, merged